const graffitiData = [
  {
    id: "1",
    city: "김포",
    locationLabel: "김포 길거리의 변압기",
    messageType: "긍정", // e.g. 긍정 / 정치 / 로맨틱 / 그림,기호 / 불만 / 외설적 / 기타
  // "실내" or "야외"
    doodleType: "스프레이 그래피티", // e.g. Marker doodle / Sticker / Paste-up / Spray graffiti
    messageText: "부모님 말씀을 잘 듣잣",
    year: 2023,
    imageUrl: "image/그래피티/B1.jpg",
  },
  {
    id: "2",
    city: "서울",
    locationLabel: "서울대입구 약국 앞 배너",
    coordinates: null,
    messageType: "불만",
 
    doodleType: "마커 낙서",
    theme: "뚱뚱글자",
    messageText: "왜! 이렇게 약국이 많은가요?",
    year: 2025,
    imageUrl: "image/통통/J16.png",
  },
  {
    id: "3",
    city: "서울",
    locationLabel: "낙성대입구 무인정산기",
    coordinates: null,
    messageType: "긍정",
 
    doodleType: "마커 낙서",
    messageText: "고맙습니다!",
    theme: "무인정산기",
    year: 2025,
    imageUrl: "image/무인정산기/F1.png",
  },
 {
    id: "4",
    city: "서울",
    locationLabel: "봉천동 골목길 벽",
    coordinates: null,
    messageType: "긍정",
 
    doodleType: "마커 낙서",
    theme: "뚱뚱글자",
    messageText: "애기가 자라고 있으니 재미있게 놀길 바람니다!?",
    year: 2025,
    imageUrl: "image/통통/J17.png",
  },
  {
    id: "5",
    city: "서울",
    locationLabel: "봉천동 골목길 벽",
    coordinates: null,
    messageType: "긍정",
 
    doodleType: "마커 낙서",
    theme: "뚱뚱글자",
    messageText: "그레도 오죽했을까요!",
    year: 2025,
    imageUrl: "image/통통/J23.png",
  },
  {
    id: "6",
    city: "서울",
    locationLabel: "서울대입구 골목길 벽",
    coordinates: null,
    messageType: "불만",
 
    doodleType: "마커 낙서",
    messageText: "자축인묘진사요미신유못해, 너나 잘해",
    year: 2025,
    imageUrl: "image/기타/C10.png",


  },
{
    id: "7",
    city: "서울",
    locationLabel: "서울대입구 골목길 벽",
    coordinates: { lat: 37.5512, lng: 126.9214 }, // optional
    messageType: "기타", // e.g. Encouraging / Political / Romantic / Random / Angry / etc.
  // "실내" or "야외"
    doodleType: "Spray graffiti", // e.g. Marker doodle / Sticker / Paste-up / Spray graffiti
    messageText: "공사장 가벽의 낙서들 1",
    theme: "공사장 가벽",
    year: 2024,
    imageUrl: "image/공사장/A2.png",
  },
  {
    id: "8",
    city: "서울",
    locationLabel: "서울대입구 공사장 가벽",
    coordinates: null,
    messageType: "Political",
 
    doodleType: "Paint doodle",
    messageText: "공사장 가벽의 낙서들 2",
    year: 2023,
    imageUrl: "image/공사장/A3.png",
  },
  {
    id: "9",
    city: "서울",
    locationLabel:  "서울대입구 공사장 가벽",
    coordinates: null,
    messageType: "Romantic",
    doodleType: "Pencil Sketch",
    messageText: " 파 라",
    year: 2022,
    imageUrl: "image/공사장/A5.png",
  },
 {
    id: "10",
    city: "서울",
    locationLabel:  "서울대입구 공사장 가벽",
    coordinates: null,
    messageType: "Romantic",
    doodleType: "Glue Residue",
    messageText: "그러면 도대체",
    year: 2022,
    imageUrl: "image/공사장/A4.png",
  },
  {
    id: "11",
    city: "서울",
    locationLabel: "서울대입구 공사장 가벽",
    coordinates: null,
    messageType: "Random",
 
    doodleType: "Sticker",
    messageText: "니가 그렇게 했기 때문에 검사 불기소",
    year: 2023,
    imageUrl: "image/공사장/A6.png",
  },
  {
    id: "12",
    city: "서울",
    locationLabel: "서울대입구 공사장 가벽",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "조금 과 적당히",
    year: 2021,
    imageUrl: "image/공사장/A7.png",
  },
  {
    id: "13",
    city: "서울",
    locationLabel: "서울대입구 공사장 가벽",
    coordinates: null,
    messageType: "Playful",
    doodleType: "Marker doodle",
    messageText: "우, 담합은 하지마시길",
    year: 2022,
    imageUrl: "image/공사장/A8.png",
  },
    {
    id: "14",
    city: "서울",
    locationLabel: "서울대입구 공사장 가벽",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "안전 명심",
    year: 2021,
    imageUrl: "image/공사장/A9.png",
  },
    {
    id: "15",
    city: "서울",
    locationLabel: "서울대입구 공사장 가벽",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "아무리 어쨋튼 어련히 그러니까, 알고보니 똑같은 언어로 다툰이.",
    year: 2021,
    imageUrl: "image/공사장/A10.png",
  },
    {
    id: "16",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "<span class='hanja-fallback'>休</span>(휴) <span class='hanja-fallback'>忍仁人</span>(인인인)",
    year: 2021,
    imageUrl: "image/공사장/A11.png",
  },
    {
    id: "17",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "열심히 일하고",
    year: 2025,
    imageUrl: "image/공사장/A12.png",
  },
      {
    id: "17a",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "어차피 Games ov-r",
    year: 2025,
    imageUrl: "image/공사장/A23.png",
  },
      {
    id: "17b",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "아ㅍ 노파심",
    year: 2025,
    imageUrl: "image/공사장/A22.png",
  },
      {
    id: "17c",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "진드기 조심",
    year: 2025,
    imageUrl: "image/공사장/A21.png",
  },
        {
    id: "17d",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "고맙습니다 귀주대첩 덕분에!",
    year: 2025,
    imageUrl: "image/공사장/A20.png",
  },
  {
    id: "17e",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "밥은(먹)드시고 하세요",
    year: 2025,
    imageUrl: "image/공사장/A18.png",
  },
    {
    id: "18",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "제발 혼자서 어려우니, 건강검진 꼭 받으세요 <3",
    year: 2021,
    imageUrl: "image/통통/벽_야외_1688 2.png",
  },
    {
    id: "19",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "맛있으니 걱정 끝! :), 고마워요~",
        theme: "뚱뚱글자",
    year: 2021,
    imageUrl: "image/통통/J21.png",
  },
    {
    id: "21",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "신토불이",
    year: 2021,
    imageUrl: "image/공사장/A13.png",
  },
    {
    id:  "22",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "외설적",
 
    doodleType: "스프레이 그래피티",
    messageText: "sex",
    year: 2021,
    imageUrl: "image/기타/C11.png",
  },
    {
    id: "23",
    city: "서울",
    locationLabel: "홍익대학교",
    coordinates: null,
    messageType: "응원",
 
    doodleType: "스티커",
    messageText: "가장 빛나는 별은 아직 발견되지 않은 ㄹ",
    year: 2021,
    imageUrl: "image/기타/C12.png",
  },
 {
    id:  "24",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "손해주 바보",
        theme: "벽돌벽",
    year: 2021,
    imageUrl: "image/벽돌벽/G1.png",
  },
      {
    id:  "25",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "샤낙서",
    year: 2021,
    imageUrl: "image/기타/C13.png",
  },
      {
    id:   "26",
    city: "부산",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "쓰레기 버리시면 양심도 버려진다",
    year: 2021,
    imageUrl: "image/기타/C14.png",
  },
      {
    id: "27",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "화장실 낙서 1",
    year: 2021,
    imageUrl: "image/기타/C16.png",
  },
      {
    id:   "28",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "화장실 낙서 2",
    year: 2021,
    imageUrl: "image/기타/C17.png",
  },
      {
    id:  "29",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "화장실 낙서 3",
    year: 2021,
    imageUrl: "image/기타/C18.png",
  },
      {
    id:  "30",
    city: "후쿠오카",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "BOSS",
    year: 2021,
    imageUrl: "image/그래피티/8.jpg",
  },
      {
    id: "31",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "BASASA",
    year: 2021,
    imageUrl: "image/그래피티/B5.jpg",
  },
      {
    id:  "32",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "갑질하냐",
    year: 2021,
    imageUrl: "image/공사장/A1.png",
  },
      {
    id:  "33",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "공사장 가벽 그래피티",
    year: 2021,
    imageUrl: "image/그래피티/B19.jpeg",
  },
      {
    id:   "34",
    city: "호치민",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "화장실 낙서 4",
    year: 2021,
    imageUrl: "image/그래피티/B17.png",
  },
      {
    id:  "35",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "SUPERIOR 1",
    year: 2021,
    imageUrl: "image/그래피티/B3.png",
  },
      {
    id:  "36",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "SUPERIOR 2",
    year: 2021,
    imageUrl: "image/그래피티/B4.png",
  },
      {
    id: "37",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "벽 그래피티",
    year: 2021,
    imageUrl: "image/그래피티/B6.png",
  },
      {
    id: "38",
    city: "후쿠오카",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "후쿠오카 낙서",
    year: 2021,
    imageUrl: "image/그래피티/B7.png",
  },
      {
    id:  "39",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "문대의 장난꾸러기",
    year: 2021,
    imageUrl: "image/그래피티/B8.png",
  },
      {
    id: "40",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "october",
    year: 2021,
    imageUrl: "image/그래피티/B9.png",
  },
      {
    id: "41",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "doxa",
    year: 2021,
    imageUrl: "image/그래피티/B10.png",
  },
      {
    id: "42",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "국어국문",
    year: 2021,
    imageUrl: "image/그래피티/B11.png",
  },
      {
    id:  "43",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "발버둥^^*",
    year: 2021,
    imageUrl: "image/그래피티/B12.png",
  },
      {
    id: "44",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "인형과 낙서",
    year: 2021,
    imageUrl: "image/그래피티/B13.png",
  },
      {
    id:  "45",
    city: "호치민",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "푸미흥 변압기 낙서",
    year: 2021,
    imageUrl: "image/그래피티/B14.png",
  },
      {
    id:  "46",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "자유의지",
    year: 2025,
    imageUrl: "image/그래피티/B15.png",
  },
      {
    id: "47",
    city: "타이베이",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "타이베이 신호등 낙서",
    year: 2025,
    imageUrl: "image/그래피티/B16.png",
  },
        {
    id:  "47a",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "서울대입구 그래피티",
    year: 2025,
    imageUrl: "image/그래피티/B26.png",
  },
          {
    id:  "47b",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "매롱과 태그",
    year: 2025,
    imageUrl: "image/그래피티/B27.png",
  },
            {
    id:  "47c",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "부추삼겹살 그래피티",
    year: 2025,
    imageUrl: "image/그래피티/B28.png",
  },
      {
    id: "48",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 1",
    theme: "요즘 아이들",
    year: 2025,
    imageUrl: "image/놀이터/D1.png",
  },
      {
    id: "49",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 2",
    year: 2025,
    imageUrl: "image/놀이터/D2.png",
  },
      {
    id:  "50",
     city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 3",
    year: 2025,
    imageUrl: "image/놀이터/D3.png",
  },
      {
    id: "51",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 4",
        theme: "요즘 아이들",
    year: 2025,
    imageUrl: "image/놀이터/D4.png",
  },
      {
    id: "52",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 5",
        theme: "요즘 아이들",
    year: 2025,
    imageUrl: "image/놀이터/D5.png",
  },
      {
    id:  "53",
      city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 6",
            theme: "요즘 아이들",
    year: 2025,
        imageUrl: "image/놀이터/D6.png",


  },
      {
    id: "54",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 7",
            theme: "요즘 아이들",
    year: 2025,
        imageUrl: "image/놀이터/D7.png",

  },
    {
    id: "55",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 8",
            theme: "요즘 아이들",
    year: 2025,
        imageUrl: "image/놀이터/D8.png",

  },
      {
    id: "56",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 9",
            theme: "요즘 아이들",
    year: 2025,
        imageUrl: "image/놀이터/D9.png",

  },
      {
    id:  "57",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 10",
            theme: "요즘 아이들",
    year: 2025,
        imageUrl: "image/놀이터/D10.png",

  },
      {
    id: "58",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 11",
            theme: "요즘 아이들",
    year: 2025,
        imageUrl: "image/놀이터/D11.png",

  },
      {
    id:   "59",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 12",
            theme: "요즘 아이들",
    year: 2025,
    imageUrl: "image/놀이터/D12.png",
  },
      {
    id:   "60",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 13",
            theme: "요즘 아이들",
    year: 2025,
    imageUrl: "image/놀이터/D13.png",
  },
      {
    id:   "61",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 14",
            theme: "요즘 아이들",
    year: 2025,
    imageUrl: "image/놀이터/D14.png",
  },
    {
    id: "62",
     city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 15",
    year: 2025,
    imageUrl: "image/놀이터/D15.png",
  },
      {
    id: "63",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 16",
    year: 2025,
    imageUrl: "image/놀이터/D16.png",
  },
      {
    id:  "64",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 17",
    year: 2025,
    imageUrl: "image/놀이터/D17.png",
  },
      {
    id: "65",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 18",
    year: 2025,
    imageUrl: "image/놀이터/D18.png",
  },
      {
    id: "66",
     city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 19",
    year: 2025,
    imageUrl: "image/놀이터/D19.png",
  },
      {
    id:  "67",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 20",
    year: 2025,
    imageUrl: "image/놀이터/D20.png",
  },
      {
    id:   "68",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 21",
    year: 2025,
    imageUrl: "image/놀이터/D21.png",
  },
    {
    id: "69",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 22",
    year: 2025,
    imageUrl: "image/놀이터/D22.png",
  },
      {
    id: "70",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 23",
    year: 2025,
    imageUrl: "image/놀이터/D23.png",
  },
      {
    id:   "71",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 24",
    year: 2025,
    imageUrl: "image/놀이터/D24.png",
  },
      {
    id:   "72",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 25",
    year: 2025,
    imageUrl: "image/놀이터/D25.png",
  },
      {
    id:   "73",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    theme: "뚱뚱글자", 
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 26",
    year: 2025,
    imageUrl: "image/놀이터/D26.png",
  },
      {
    id:   "74",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 27",
    year: 2025,
    imageUrl: "image/놀이터/D27.png",
  },
      {
    id: "75",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 28",
    year: 2025,
    imageUrl: "image/놀이터/D28.png",
  },
    {
    id:   "76",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 29",
    year: 2025,
    imageUrl: "image/놀이터/D29.png",
  },
      {
    id:   "77",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 30",
    year: 2025,
    imageUrl: "image/놀이터/D30.png",
  },
      {
    id:   "78",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 31",
    year: 2025,
    imageUrl: "image/놀이터/D31.png",
  },
      {
    id:  "79",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 32",
    year: 2025,
    imageUrl: "image/놀이터/D32.png",
  },
      {
    id: "80",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 33",
    year: 2025,
    imageUrl: "image/놀이터/D33.png",
  },
      {
    id:  "81",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 34",
    year: 2025,
    imageUrl: "image/놀이터/D34.png",
  },
      {
    id: "82",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 35",
    year: 2025,
    imageUrl: "image/놀이터/D35.png",
  },
    {
    id: "83",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 36",
    year: 2025,
    imageUrl: "image/놀이터/D36.png",
  },
      {
    id: "84",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 37",
    year: 2025,
    imageUrl: "image/놀이터/D37.png",
  },
      {
    id:  " 85",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 38",
    year: 2025,
    imageUrl: "image/놀이터/D38.png",
  },
      {
    id: "86",
     city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 39",
    year: 2025,
    imageUrl: "image/놀이터/D39.png",
  },
      {
    id: "87",
      city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 40",
    year: 2025,
    imageUrl: "image/놀이터/D40.png",
  },
      {
    id:  "88",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 41",
    year: 2025,
    imageUrl: "image/놀이터/D41.png",
  },
      {
    id: "89",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 42",
    year: 2025,
    imageUrl: "image/놀이터/D42.png",
  },
    {
    id: "90",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 43",
    year: 2025,
    imageUrl: "image/놀이터/D43.png",
  },
      {
    id: "91",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 44",
    year: 2025,
    imageUrl: "image/놀이터/D44.png",
  },
      {
    id: "91o",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 45",
    year: 2025,
    imageUrl: "image/놀이터/D45.png",
  },
      {
    id: "91n",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 46",
    year: 2025,
    imageUrl: "image/놀이터/D46.png",
  },
      {
    id: "91m",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 47",
    year: 2025,
    imageUrl: "image/놀이터/D47.png",
  },
      {
    id: "91l",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 48",
    year: 2025,
    imageUrl: "image/놀이터/D48.png",
  },
      {
    id: "91k",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 49",
    year: 2025,
    imageUrl: "image/놀이터/D49.png",
  },
      {
    id: "91j",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 50",
    year: 2025,
    imageUrl: "image/놀이터/D50.png",
  },
      {
    id: "91i",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 51",
    year: 2025,
    imageUrl: "image/놀이터/D51.png",
  },
      {
    id: "91g",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 52",
    year: 2025,
    imageUrl: "image/놀이터/D52.png",
  },
      {
    id: "91f",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 53",
    year: 2025,
    imageUrl: "image/놀이터/D53.png",
  },
      {
    id: "91e",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 54",
    year: 2025,
    imageUrl: "image/놀이터/D54.png",
  },
      {
    id: "91d",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 55",
    year: 2025,
    imageUrl: "image/놀이터/D55.png",
  },
      {
    id: "91c",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 56",
    year: 2025,
    imageUrl: "image/놀이터/D56.png",
  },
      {
    id: "91b",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 57",
    year: 2025,
    imageUrl: "image/놀이터/D57.png",
  },
      {
    id: "91a",
    city: "서울",
    locationLabel: "성현동아아파트 놀이터",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "놀이터 58",
    year: 2025,
    imageUrl: "image/놀이터/D58.png",
  },
      {
    id:  "92",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "기호",
    year: 2021,
    imageUrl: "image/그래피티/B18.jpeg",
  },
      {
    id: "93",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "대화: Talk",
    year: 2021,
    imageUrl: "image/기타/C23.jpg",
  },
      {
    id: "94",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "눈웃음",
    year: 2021,
    imageUrl: "image/기타/C44.jpeg",
  },
      {
    id:  "95",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "나무아미타불",
    year: 2021,
    imageUrl: "image/기타/C6.png",
  },
      {
    id: "96",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "□.....?",
    year: 2021,
    imageUrl: "image/기타/C5.png",
  },
      {
    id:  "97",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "B",
    year: 2021,
    imageUrl: "image/기타/C4.png",
  },
      {
    id: "98",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "^_^",
    year: 2021,
    imageUrl: "image/기타/C3.png",
  },
      {
    id:  "99",
    city: "송도",
    locationLabel: "인천 송도 코스트코",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "코스트코 낙서",
    year: 2021,
    imageUrl: "image/기타/C2.png",
  },
      {
    id: "100",
    city: "서울",
    locationLabel: "서울대학교 미술대학 51동",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "붓글씨 낙서",
    messageText: "저거멋쪄",
    year: 2021,
    imageUrl: "image/기타/C1.png",
  },
        {
    id:  "101",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "메롱",
    year: 2021,
    imageUrl: "image/그래피티/B20.png",
  },
      {
    id: "102",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "술은 조금만",
        theme: "뚱뚱글자",
    year: 2021,
    imageUrl: "image/통통/IMG_1998.png",
  },
        {
    id:  "103",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "그래피티",
    year: 2021,
    imageUrl: "image/그래피티/IMG_1999.png",
  },
      {
    id: "104",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "?끔가",
        theme: "뚱뚱글자",
    year: 2021,
    imageUrl: "image/통통/J4.png",
  },
        {
    id:  "105",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "헬멧 필수 (중요)",
    theme: "따릉이",
    year: 2021,
    imageUrl: "image/따릉이/IMG_2002.png",
  },
      {
    id: "106",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "제발 분리수거 쫌",
        theme: "뚱뚱글자",
    year: 2021,
    imageUrl: "image/통통/J3.png",
  },
        {
    id:  "107",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "먹고 싶어요",
        theme: "뚱뚱글자",
    year: 2021,
    imageUrl: "image/통통/J2.png",
  },
      {
    id: "108",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "CCTV 1566-0423",
    year: 2021,
    imageUrl: "image/공사장/A14.png",
  },
        {
    id:  "109",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "도안",
    year: 2021,
    imageUrl: "image/공사장/A15.png",
  },
        {
    id:  "111",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "신고완료",
    year: 2021,
     imageUrl: "image/기타/IMG_2054.jpg",
  },
      {
    id: "112",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "아프면 안돼요",
        theme: "뚱뚱글자",
    year: 2021,
     imageUrl: "image/통통/IMG_2055.jpg",
  },
      {
    id: "113",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "비둘기_괴사,부식 1",
    theme: "괴사한 비둘기",
    year: 2021,
     imageUrl: "image/비둘기/IMG_2059 2.jpg",
  },
      {
    id: "114",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "화장실 가는 길",
    theme: "화장실 가는 길",
    year: 2021,
     imageUrl: "image/화장실/IMG_2063.jpg",
  },
        {
    id: "115",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "덕분에 계단에서 안미끄러졌어요",
        theme: "뚱뚱글자",
    year: 2021,
     imageUrl: "image/통통/IMG_2064.jpg",
  },
          {
    id: "116",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "언제 치우실 거예요",
    year: 2021,
     imageUrl: "image/기타/IMG_2065 2.jpg",
  },
            {
    id: "118",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "비둘기_괴사,부식 2",
    theme: "괴사한 비둘기",
    year: 2021,
     imageUrl: "image/비둘기/IMG_2077.jpg",
  },
            {
    id: "119",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "쌍둥이 그래피티",
    year: 2021,
     imageUrl: "image/그래피티/IMG_2078.jpg",
  },
            {
    id: "120",
    city: "의정부",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "별스위치",
    year: 2021,
     imageUrl: "image/기타/IMG_2120.jpg",
  },
            {
    id: "121",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "주유소 그래피티",
    year: 2021,
     imageUrl: "image/그래피티/B23.jpg",
  },
            {
    id: "122",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "소독한 것이 죄가 된다면",
    year: 2021,
     imageUrl: "image/기타/IMG_2154.jpg",
  },
            {
    id: "123",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "무조건 달린다고 해서, 헬멧",
    year: 2021,
     imageUrl: "image/따릉이/IMG_2155.jpg",
  },
            {
    id: "124",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "헬멧도 안쓰고 자기들이 왕인 것 마냥 쯔쯔.....",
    year: 2021,
     imageUrl: "image/따릉이/IMG_2157 17.22.07.jpg",
  },
            {
    id: "126",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
       theme: "괴사한 비둘기",
    messageText: "비둘기 먹이주지 마시라구요 제발",
    year: 2021,
     imageUrl: "image/비둘기/IMG_2158.jpg",
  },
            {
    id: "127",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "야구연습장 낙서",
        theme: "뚱뚱글자",
    year: 2021,
     imageUrl: "image/통통/IMG_2168.jpg",
  },
            {
    id: "128",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "무심코 붙는 순간",
        theme: "무인정산기",

    year: 2021,
     imageUrl: "image/무인정산기/IMG_2170.jpg",
  },
            {
    id: "129",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "담배 꽁초 x 불이 벼에, 소화기 중요 ",
        theme: "무인정산기",

    year: 2021,
     imageUrl: "image/무인정산기/IMG_2171.jpg",
  },
            {
    id: "130",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "벽돌 벽 그래피티",
    year: 2021,
     imageUrl: "image/그래피티/IMG_2172.jpg",
  },
            {
    id: "131",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "다치지나 않을까 아프지나 않을까 걱정하는 저의 마음 저만 아는가요 <3 언제나",
        theme: "뚱뚱글자",
    year: 2021,
     imageUrl: "image/통통/IMG_2173.jpg",
  },
              {
    id: "132",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "아가 조심하거라 제발",
        theme: "뚱뚱글자",
    year: 2021,
     imageUrl: "image/통통/IMG_2174.jpg",
  },
            {
    id: "134",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "대한민국 고맙습니다, 덕분에",
        theme: "뚱뚱글자",
    year: 2021,
     imageUrl: "image/통통/IMG_2176.jpg",
  },
              {
    id: "135",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "방역, 모기 진드기 해로운 해충",
    year: 2021,
     imageUrl: "image/기타/IMG_2177.jpg",
  },
            {
    id: "136",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "King South 4 nwave",
    year: 2021,
     imageUrl: "image/그래피티/B25.jpg",
  },
            {
    id: "137",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "바람때문에 모두 날라가면 어찌하오리오, 그러면! 담밸 팔면 안돼지",
        theme: "뚱뚱글자",
    year: 2021,
     imageUrl: "image/통통/IMG_2188.jpg",
  },
              {
    id: "138",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "조금은 더러워도 괜찮아요!, 제발 강건너",
    year: 2021,
     imageUrl: "image/기타/IMG_2193.jpg",
  },
            {
    id: "139",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "언제",
    theme: "의류수거함",
    year: 2021,
     imageUrl: "image/의류수거함/IMG_2189.jpg",
  },
              {
    id: "139a",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "옷",
        theme: "의류수거함",
    year: 2021,
     imageUrl: "image/의류수거함/IMG_2407 2.png",
  },
            {
    id: "140",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "애기, 차라리, 바람이 불면?, 청소도 재미있어야 하죠 조금이나마 분리수거 쫌쫌, 아기가 살아요",
        theme: "의류수거함",
    year: 2021,
     imageUrl: "image/의류수거함/IMG_2194.jpg",
  },
              {
    id: "141",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "종량제봉지 넣지마!",
        theme: "의류수거함",
    year: 2021,
     imageUrl: "image/의류수거함/IMG_2195.jpg",
  },
            {
    id: "142",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "언제나 치워주셔서 <3",
        theme: "의류수거함",
    year: 2021,
     imageUrl: "image/의류수거함/IMG_2196.jpg",
  },
            {
    id: "143",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "야!껴쓰시길!",
    theme: ["의류수거함","뚱뚱글자"],
    year: 2021,
     imageUrl: "image/의류수거함/IMG_2197.jpg",
  },
              {
    id: "144",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "안전을 요한다면",
        theme: "의류수거함",
    year: 2021,
     imageUrl: "image/의류수거함/IMG_2198.jpg",
  },
            {
    id: "145",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "조금이나마 도와주세요!, 약속 ^_^",
        theme: "뚱뚱글자",
    year: 2021,
     imageUrl: "image/통통/IMG_2199.jpg",
  },
            {
    id: "146",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "분리수거를! 스티로폴 -> 스티로폼",
        theme: "뚱뚱글자",
    year: 2021,
     imageUrl: "image/통통/IMG_2200.jpg",
  },
              {
    id: "147",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "너때문에 인도(보도)가 사라졌짢아!, 저는요 후를 알고있기 때문에 어차피",
    year: 2021,
     imageUrl: "image/공사장/IMG_2201.jpg",
  },
            {
    id: "148",
    city: "영등포",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "아저씨 그래피티",
    year: 2021,
     imageUrl: "image/그래피티/IMG_9126.jpg",
  },
            {
    id: "149",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "스티커",
    
    messageText: "덕지덕지",
    year: 2021,
     imageUrl: "image/기타/IMG_9335.jpg",
  },
              {
    id: "150",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "표지판 덕지덕지",
    year: 2021,
     imageUrl: "image/기타/IMG_9840.jpg",
  },
  ////
              {
    id: "151",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "주차금지",
    theme: "벽돌벽",
    year: 2021,
     imageUrl: "image/벽돌벽/IMG_2428.png",
  },
            {
    id: "152",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "마커 낙서",
    messageText: "부식(썩으니까 괴사",
    theme: "괴사한 비둘기",
    year: 2021,
     imageUrl: "image/비둘기/KakaoTalk_Photo_2025-12-13-17-45-45 007.jpeg",
  },
              {
    id: "153",
    city: "서울",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "똥은 부식 괴사",
    theme: "괴사한 비둘기",
    year: 2021,
     imageUrl: "image/비둘기/KakaoTalk_Photo_2025-12-13-17-45-46 009.jpeg",
  },
              {
    id: "154",
    city: "영등포",
    locationLabel: "Gongguan bridge pillar",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "Spray graffiti",
    messageText: "따봉하트",
        theme: "뚱뚱글자",
    year: 2021,
     imageUrl: "image/통통/IMG_2409.png",
  },
            {
    id: "155",
    city: "서울",
    locationLabel: "서울신봉초등학교",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "스티커",
    messageText: "서용 바보",
    year: 2025,
    theme: "벽돌벽",
     imageUrl: "image/벽돌벽/IMG_2431.png",
  },
              {
    id: "156",
    city: "서울",
    locationLabel: "서울신봉초등학교",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "스티커",
    messageText: "준 바보",
    year: 2025,
    theme: "벽돌벽",
     imageUrl: "image/벽돌벽/IMG_2430.png",
  },
              {
    id: "157",
    city: "서울",
    locationLabel: "서울신봉초등학교",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "스티커",
    messageText: " ↑D",
    year: 2025,
    theme: "벽돌벽",
     imageUrl: "image/벽돌벽/IMG_2432.png",
  },
            {
    id: "158",
city: "서울",
    locationLabel: "서울신봉초등학교",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "스티커",
    messageText: "SO BEAST",
    year: 2025,
    theme: "벽돌벽",
     imageUrl: "image/벽돌벽/IMG_2433.png",
  },
              {
    id: "159",
    city: "서울",
    locationLabel: "서울신봉초등학교",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "스티커",
    messageText: "판박이1",
    year: 2025,
    theme: "벽돌벽",
     imageUrl: "image/벽돌벽/IMG_2440.png",
  },
              {
    id: "160",
    city: "서울",
    locationLabel: "서울신봉초등학교",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "스티커",
    messageText: "판박이2",
    year: 2025,
    theme: "벽돌벽",
     imageUrl: "image/벽돌벽/IMG_2441.png",
  },
            {
    id: "161",
    city: "서울",
    locationLabel: "서울신봉초등학교",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "스티커",
    messageText: "시코라",
    year: 2025,
    theme: "벽돌벽",
     imageUrl: "image/벽돌벽/IMG_2445 2.png",
  },
              {
    id: "162",
    city: "서울",
    locationLabel: "서울신봉초등학교",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "스티커",
    messageText: "영구맹구짱구응구 크크크",
    year: 2025,
    theme: "벽돌벽",
     imageUrl: "image/벽돌벽/IMG_2447 2.png",
  },
                {
    id: "163",
    city: "서울",
    locationLabel: "서울신봉초등학교",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "스티커",
    messageText: "판박이3",
    year: 2025,
    theme: "벽돌벽",
     imageUrl: "image/벽돌벽/IMG_2448 2.png",
  },
                  {
    id: "164",
    city: "서울",
    locationLabel: "서울신봉초등학교",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "스티커",
    messageText: "판박이4",
    year: 2025,
    theme: "벽돌벽",
     imageUrl: "image/벽돌벽/IMG_2449 2.png",
  },
                  {
    id: "165",
    city: "서울",
    locationLabel: "서울신봉초등학교",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "스티커",
    messageText: "판박이5",
    year: 2025,
    theme: "벽돌벽",
     imageUrl: "image/벽돌벽/IMG_2450 2.png",
  },
                  {
    id: "166",
    city: "서울",
    locationLabel: "서울신봉초등학교",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "스티커",
    messageText: "판박이6",
    year: 2025,
    theme: "벽돌벽",
     imageUrl: "image/벽돌벽/IMG_2451 2.png",
  },
                    {
    id: "167",
    city: "서울",
    locationLabel: "서울신봉초등학교",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "스티커",
    messageText: "3학년",
    year: 2025,
    theme: "벽돌벽",
     imageUrl: "image/벽돌벽/IMG_2452 2.png",
  },
  {
    id: "168",
    city: "서울",
    locationLabel: "서울신봉초등학교",
    coordinates: null,
    messageType: "Encouraging",
 
    doodleType: "스티커",
    messageText: "니미럴",
    year: 2025,
    theme: "벽돌벽",
     imageUrl: "image/벽돌벽/스크린샷 2025-12-13 22.47.01.png",
  },
  
];

//"벽돌벽", -3
//
